# Site settings
course_name: "EECS 467: Autonomous Robotics Design Experience"
course_description: "Software methods and implementation for robot perception, world mapping, and control, using physical robots. Topics include: sensors, sensor processing, control, motion planning, localization and mapping, and forward and inverse kinematics. Multiple team projects, culminating in a major design experience (MDE) project."
course_semester: "Winter 2026"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://um-eecs467.github.io/" # the base hostname & protocol for your site

schoolname: "UM"
schoolurl: "https://umich.edu"
twitter_username:  

address: |
    University of Michigan, Ann Arbor

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
